#define TILE_SIZE 64
#define MAP_NUM_ROWS 13 
#define MAP_NUM_COLS 20

#define PI 3.14159265
#define TWO_PI 0.28318530
#define WINDOW_WIDTH MAP_NUM_COLS * TILE_SIZE
#define WINDOW_HEIGHT MAP_NUM_ROWS * TILE_SIZE

#define FOV_ANGLE (60 * (PI / 180))
#define NUM_RAYS WINDOW_WIDTH

#define MINIMAP_SCALE_FACTOR 1.0

#define FPS 30
#define FRAME_TIME_LENGTH (1000 / FPS)
